#!/bin/bash
set -e

SRC_DIR=$(realpath $(dirname "$0"))
GOCACHE=$(realpath ~/.cache)
APP=${SRC_DIR##*/}

# docker pull golang:latest
docker run --rm \
        -v "$SRC_DIR":/go/src/$APP \
        -v "$GOCACHE":"/.cache" \
        -w /go/src/$APP \
        -u $(id -u):$(id -g) \
        golang:latest \
        ./build $@
